baseURL = "https://r-finance.github.io/"
languageCode = "en-us"
title = "R/Finance Conference"
publishDir = "../docs"

theme = ["hugo-rfinance-theme", "hugo-universal-theme"]

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "About"
    url  = "/about/"
    weight = 2

[[menu.main]]
    identifier = "cfp"
    name = "CFP"
    url  = "/cfp/"
    weight = 3

[[menu.main]]
    identifier = "sponsorship"
    name = "Sponsors"
    url  = "/sponsors/"
    weight = 4

[params.welcome]
    title = "Applied Finance with R"

[params.features]
    enable = true

[params.committee]
    enable_footer = true

[params]
    style = "blue"
    logo = "img/Rfinance_logo.png"
